# Generated by Django 5.1.4 on 2025-01-05 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
    ]
