# Generated by Django 5.1.4 on 2025-01-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='date_field',
            field=models.CharField(max_length=15, null=True, verbose_name='Дата создания'),
        ),
    ]
