# Generated by Django 5.1.4 on 2024-12-23 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='description',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
    ]
