# Generated by Django 5.1.4 on 2024-12-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_team_description_remove_team_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
