# Generated by Django 5.1.4 on 2024-12-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_birth',
        ),
        migrations.AddField(
            model_name='user',
            name='accept_invite',
            field=models.BooleanField(default=False, verbose_name='Принимать приглашения в команду'),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на ВУЗ/организацию'),
        ),
        migrations.AddField(
            model_name='user',
            name='post',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_user',
            field=models.BooleanField(default=False, verbose_name='Верифицированный пользователь'),
        ),
        migrations.AddField(
            model_name='user',
            name='vuz_name',
            field=models.CharField(max_length=15, null=True, verbose_name='Название ВУЗа/организации'),
        ),
    ]
