# Generated by Django 5.1.4 on 2024-12-25 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MootCourt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('background', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mootcourt_images/')),
                ('arbitrators', models.ManyToManyField(blank=True, related_name='arbitrator_mootcourts', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_mootcourts', to=settings.AUTH_USER_MODEL)),
                ('senior_arbitrators', models.ManyToManyField(blank=True, related_name='senior_arbitrator_mootcourts', to=settings.AUTH_USER_MODEL)),
                ('teams', models.ManyToManyField(blank=True, related_name='mootcourts', to='users.team')),
            ],
            options={
                'verbose_name': 'Муткорт',
                'verbose_name_plural': 'Муткорты',
            },
        ),
    ]
