# Generated by Django 5.1.4 on 2025-04-16 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MootCourtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mootcourt_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('mootcourt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.mootcourt', verbose_name='Муткорт')),
            ],
        ),
    ]
